### ISSUE TITLE
Broken with Commanded 0.19

### ISSUE THREAD

**Issue by KazW** [commanded/commanded-swarm-registry#1]
Interim fix:
```elixir
{:commanded, "~> 0.19", override: true},
{:commanded_swarm_registry, "~> 0.2",
github: "commanded/commanded-swarm-registry", ref: "b48e18b"}
```

Cheers! 🍻

**Comment by slashdotdash** [comment]
Thanks for letting me know @KazW, I'd forgotten that this was impacted by Commanded v0.19 changes.

I've now [published v0.3.0 to Hex](https://hex.pm/packages/commanded_swarm_registry/0.3.0).
